USE [master]
GO

CREATE DATABASE [DapperExampleDB]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'DapperExampleDB', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL15.MSSQLSERVER\MSSQL\DATA\DapperExampleDB.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'DapperExampleDB_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL15.MSSQLSERVER\MSSQL\DATA\DapperExampleDB_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
 WITH CATALOG_COLLATION = DATABASE_DEFAULT
GO
ALTER DATABASE [DapperExampleDB] SET COMPATIBILITY_LEVEL = 150
GO
IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [DapperExampleDB].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO
ALTER DATABASE [DapperExampleDB] SET ANSI_NULL_DEFAULT OFF 
GO
ALTER DATABASE [DapperExampleDB] SET ANSI_NULLS OFF 
GO
ALTER DATABASE [DapperExampleDB] SET ANSI_PADDING OFF 
GO
ALTER DATABASE [DapperExampleDB] SET ANSI_WARNINGS OFF 
GO
ALTER DATABASE [DapperExampleDB] SET ARITHABORT OFF 
GO
ALTER DATABASE [DapperExampleDB] SET AUTO_CLOSE OFF 
GO
ALTER DATABASE [DapperExampleDB] SET AUTO_SHRINK OFF 
GO
ALTER DATABASE [DapperExampleDB] SET AUTO_UPDATE_STATISTICS ON 
GO
ALTER DATABASE [DapperExampleDB] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO
ALTER DATABASE [DapperExampleDB] SET CURSOR_DEFAULT  GLOBAL 
GO
ALTER DATABASE [DapperExampleDB] SET CONCAT_NULL_YIELDS_NULL OFF 
GO
ALTER DATABASE [DapperExampleDB] SET NUMERIC_ROUNDABORT OFF 
GO
ALTER DATABASE [DapperExampleDB] SET QUOTED_IDENTIFIER OFF 
GO
ALTER DATABASE [DapperExampleDB] SET RECURSIVE_TRIGGERS OFF 
GO
ALTER DATABASE [DapperExampleDB] SET  DISABLE_BROKER 
GO
ALTER DATABASE [DapperExampleDB] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO
ALTER DATABASE [DapperExampleDB] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO
ALTER DATABASE [DapperExampleDB] SET TRUSTWORTHY OFF 
GO
ALTER DATABASE [DapperExampleDB] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO
ALTER DATABASE [DapperExampleDB] SET PARAMETERIZATION SIMPLE 
GO
ALTER DATABASE [DapperExampleDB] SET READ_COMMITTED_SNAPSHOT OFF 
GO
ALTER DATABASE [DapperExampleDB] SET HONOR_BROKER_PRIORITY OFF 
GO
ALTER DATABASE [DapperExampleDB] SET RECOVERY FULL 
GO
ALTER DATABASE [DapperExampleDB] SET  MULTI_USER 
GO
ALTER DATABASE [DapperExampleDB] SET PAGE_VERIFY CHECKSUM  
GO
ALTER DATABASE [DapperExampleDB] SET DB_CHAINING OFF 
GO
ALTER DATABASE [DapperExampleDB] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO
ALTER DATABASE [DapperExampleDB] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO
ALTER DATABASE [DapperExampleDB] SET DELAYED_DURABILITY = DISABLED 
GO
EXEC sys.sp_db_vardecimal_storage_format N'DapperExampleDB', N'ON'
GO
ALTER DATABASE [DapperExampleDB] SET QUERY_STORE = OFF
GO
USE [DapperExampleDB]
GO
/****** Object:  Table [dbo].[User]    Script Date: 8/13/2021 4:59:41 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[User](
	[UserID] [int] IDENTITY(1,1) NOT NULL,
	[Name] [nvarchar](20) NOT NULL,
	[Surname] [nvarchar](20) NOT NULL,
	[Email] [nvarchar](80) NOT NULL,
	[InsertDate] [datetime] NOT NULL,
 CONSTRAINT [PK_User] PRIMARY KEY CLUSTERED 
(
	[UserID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
USE [master]
GO
ALTER DATABASE [DapperExampleDB] SET  READ_WRITE 
GO
